import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CMS | Learn Something New</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello Guys!</main>
    </div>
  );
}
