import Head from "next/head";
import NavBar from "../components/navbar";
import { getSession } from "next-auth/react";

import MyCourses from "../components/myCourses";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CMS | Learn Something New</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />

        <MyCourses />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  if (session) {
    return { props: { session } };
  } else {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
}
